# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!
from operator import eq

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QDragEnterEvent, QDropEvent
from PyQt5.QtWidgets import QFrame, QLabel

import gui.icon_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(389, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stack = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stack.sizePolicy().hasHeightForWidth())
        self.stack.setSizePolicy(sizePolicy)
        self.stack.setObjectName("stack")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_bubble = QtWidgets.QFrame(self.page_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_bubble.sizePolicy().hasHeightForWidth())
        self.frame_bubble.setSizePolicy(sizePolicy)
        self.frame_bubble.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bubble.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bubble.setObjectName("frame_bubble")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_bubble)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.hLayout_bubble = QtWidgets.QHBoxLayout()
        self.hLayout_bubble.setObjectName("hLayout_bubble")
        self.label_bubble = QtWidgets.QLabel(self.frame_bubble)
        self.label_bubble.setObjectName("label_bubble")
        self.hLayout_bubble.addWidget(self.label_bubble)
        self.pushButton_bubble = QtWidgets.QPushButton(self.frame_bubble)
        self.pushButton_bubble.setObjectName("pushButton_bubble")
        self.hLayout_bubble.addWidget(self.pushButton_bubble)
        self.gridLayout_7.addLayout(self.hLayout_bubble, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_bubble)
        self.box_database = QtWidgets.QGroupBox(self.page_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_database.sizePolicy().hasHeightForWidth())
        self.box_database.setSizePolicy(sizePolicy)
        self.box_database.setObjectName("box_database")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.box_database)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_box = QtWidgets.QFrame(self.box_database)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_box.sizePolicy().hasHeightForWidth())
        self.frame_box.setSizePolicy(sizePolicy)
        self.frame_box.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_box.setObjectName("frame_box")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_box)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.hLayout_box = QtWidgets.QHBoxLayout()
        self.hLayout_box.setObjectName("hLayout_box")
        self.label_id = QtWidgets.QLabel(self.frame_box)
        self.label_id.setObjectName("label_id")
        self.hLayout_box.addWidget(self.label_id)
        self.hlayout_id = QtWidgets.QHBoxLayout()
        self.hlayout_id.setContentsMargins(10, -1, -1, -1)
        self.hlayout_id.setSpacing(20)
        self.hlayout_id.setObjectName("hlayout_id")
        self.edit_id = QtWidgets.QLineEdit(self.frame_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_id.sizePolicy().hasHeightForWidth())
        self.edit_id.setSizePolicy(sizePolicy)
        self.edit_id.setMinimumSize(QtCore.QSize(0, 0))
        self.edit_id.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edit_id.setObjectName("edit_id")
        self.hlayout_id.addWidget(self.edit_id)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayout_id.addItem(spacerItem)
        self.check_id = QtWidgets.QCheckBox(self.frame_box)
        self.check_id.setObjectName("check_id")
        self.hlayout_id.addWidget(self.check_id)
        self.hLayout_box.addLayout(self.hlayout_id)
        self.gridLayout_12.addLayout(self.hLayout_box, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_box, 0, 0, 1, 1)
        self.pushButton_dbsetting = QtWidgets.QPushButton(self.box_database)
        self.pushButton_dbsetting.setObjectName("pushButton_dbsetting")
        self.gridLayout_13.addWidget(self.pushButton_dbsetting, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.box_database)
        self.pushButton_shortcuts = QtWidgets.QPushButton(self.page_main)
        self.pushButton_shortcuts.setObjectName("pushButton_shortcuts")
        self.verticalLayout.addWidget(self.pushButton_shortcuts)
        self.frame_board = Board(self.page_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_board.sizePolicy().hasHeightForWidth())
        self.frame_board.setSizePolicy(sizePolicy)
        self.frame_board.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_board.setMaximumSize(QtCore.QSize(329, 250))
        self.frame_board.setAcceptDrops(True)
        self.frame_board.setStyleSheet("background: no-repeat center/20% url(:/icon/drag.png)")
        self.frame_board.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_board.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_board.setObjectName("frame_board")
        self.verticalLayout.addWidget(self.frame_board)
        self.box_image = QtWidgets.QGroupBox(self.page_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_image.sizePolicy().hasHeightForWidth())
        self.box_image.setSizePolicy(sizePolicy)
        self.box_image.setObjectName("box_image")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.box_image)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_image = QtWidgets.QFrame(self.box_image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_image.sizePolicy().hasHeightForWidth())
        self.frame_image.setSizePolicy(sizePolicy)
        self.frame_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_image.setObjectName("frame_image")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_image)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setHorizontalSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_height = QtWidgets.QFrame(self.frame_image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_height.sizePolicy().hasHeightForWidth())
        self.frame_height.setSizePolicy(sizePolicy)
        self.frame_height.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_height.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_height.setObjectName("frame_height")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_height)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.hLayout_height = QtWidgets.QHBoxLayout()
        self.hLayout_height.setSpacing(5)
        self.hLayout_height.setObjectName("hLayout_height")
        self.label_height = QtWidgets.QLabel(self.frame_height)
        self.label_height.setObjectName("label_height")
        self.hLayout_height.addWidget(self.label_height)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_height.addItem(spacerItem1)
        self.label_heightValue = QtWidgets.QLabel(self.frame_height)
        self.label_heightValue.setMinimumSize(QtCore.QSize(60, 0))
        self.label_heightValue.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_heightValue.setText("")
        self.label_heightValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_heightValue.setObjectName("label_heightValue")
        self.hLayout_height.addWidget(self.label_heightValue)
        self.label_heightPx = QtWidgets.QLabel(self.frame_height)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_heightPx.sizePolicy().hasHeightForWidth())
        self.label_heightPx.setSizePolicy(sizePolicy)
        self.label_heightPx.setMinimumSize(QtCore.QSize(25, 0))
        self.label_heightPx.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_heightPx.setObjectName("label_heightPx")
        self.hLayout_height.addWidget(self.label_heightPx)
        self.gridLayout_9.addLayout(self.hLayout_height, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_height, 1, 0, 1, 1)
        self.frame_ratio = QtWidgets.QFrame(self.frame_image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_ratio.sizePolicy().hasHeightForWidth())
        self.frame_ratio.setSizePolicy(sizePolicy)
        self.frame_ratio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ratio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ratio.setObjectName("frame_ratio")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_ratio)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.hLayout_ratio = QtWidgets.QHBoxLayout()
        self.hLayout_ratio.setSpacing(5)
        self.hLayout_ratio.setObjectName("hLayout_ratio")
        self.label_ratio = QtWidgets.QLabel(self.frame_ratio)
        self.label_ratio.setObjectName("label_ratio")
        self.hLayout_ratio.addWidget(self.label_ratio)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_ratio.addItem(spacerItem2)
        self.edit_ratioValue = QtWidgets.QLineEdit(self.frame_ratio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_ratioValue.sizePolicy().hasHeightForWidth())
        self.edit_ratioValue.setSizePolicy(sizePolicy)
        self.edit_ratioValue.setMinimumSize(QtCore.QSize(70, 0))
        self.edit_ratioValue.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_ratioValue.setObjectName("edit_ratioValue")
        self.hLayout_ratio.addWidget(self.edit_ratioValue)
        self.label_ratioPx = QtWidgets.QLabel(self.frame_ratio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ratioPx.sizePolicy().hasHeightForWidth())
        self.label_ratioPx.setSizePolicy(sizePolicy)
        self.label_ratioPx.setMinimumSize(QtCore.QSize(25, 0))
        self.label_ratioPx.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_ratioPx.setObjectName("label_ratioPx")
        self.hLayout_ratio.addWidget(self.label_ratioPx)
        self.gridLayout_10.addLayout(self.hLayout_ratio, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_ratio, 2, 0, 1, 1)
        self.frame_width = QtWidgets.QFrame(self.frame_image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_width.sizePolicy().hasHeightForWidth())
        self.frame_width.setSizePolicy(sizePolicy)
        self.frame_width.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_width.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_width.setObjectName("frame_width")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_width)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.hLayout_width = QtWidgets.QHBoxLayout()
        self.hLayout_width.setSpacing(5)
        self.hLayout_width.setObjectName("hLayout_width")
        self.label_width = QtWidgets.QLabel(self.frame_width)
        self.label_width.setObjectName("label_width")
        self.hLayout_width.addWidget(self.label_width)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_width.addItem(spacerItem3)
        self.label_widthValue = QtWidgets.QLabel(self.frame_width)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_widthValue.sizePolicy().hasHeightForWidth())
        self.label_widthValue.setSizePolicy(sizePolicy)
        self.label_widthValue.setMinimumSize(QtCore.QSize(60, 0))
        self.label_widthValue.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_widthValue.setText("")
        self.label_widthValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_widthValue.setObjectName("label_widthValue")
        self.hLayout_width.addWidget(self.label_widthValue)
        self.label_widthPx = QtWidgets.QLabel(self.frame_width)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_widthPx.sizePolicy().hasHeightForWidth())
        self.label_widthPx.setSizePolicy(sizePolicy)
        self.label_widthPx.setMinimumSize(QtCore.QSize(25, 0))
        self.label_widthPx.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_widthPx.setObjectName("label_widthPx")
        self.hLayout_width.addWidget(self.label_widthPx)
        self.gridLayout_8.addLayout(self.hLayout_width, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_width, 0, 0, 1, 1)
        self.pushButton_calibrate = QtWidgets.QPushButton(self.frame_image)
        self.pushButton_calibrate.setObjectName("pushButton_calibrate")
        self.gridLayout_11.addWidget(self.pushButton_calibrate, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_image, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.box_image)
        self.pushButton_start = QtWidgets.QPushButton(self.page_main)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        self.stack.addWidget(self.page_main)
        self.page_database = QtWidgets.QWidget()
        self.page_database.setObjectName("page_database")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_database)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.box_setting = QtWidgets.QGroupBox(self.page_database)
        self.box_setting.setObjectName("box_setting")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.box_setting)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.table = QtWidgets.QTableWidget(self.box_setting)
        self.table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table.setShowGrid(True)
        self.table.setGridStyle(QtCore.Qt.SolidLine)
        self.table.setWordWrap(True)
        self.table.setCornerButtonEnabled(True)
        self.table.setObjectName("table")
        self.table.setColumnCount(1)
        self.table.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        self.gridLayout_6.addWidget(self.table, 0, 0, 1, 1)
        self.hLayout_setting = QtWidgets.QHBoxLayout()
        self.hLayout_setting.setObjectName("hLayout_setting")
        self.pushButton_cancel = QtWidgets.QPushButton(self.box_setting)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.hLayout_setting.addWidget(self.pushButton_cancel)
        self.pushButton_apply = QtWidgets.QPushButton(self.box_setting)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.hLayout_setting.addWidget(self.pushButton_apply)
        self.gridLayout_6.addLayout(self.hLayout_setting, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.box_setting, 0, 0, 1, 1)
        self.stack.addWidget(self.page_database)
        self.page_shortcuts = QtWidgets.QWidget()
        self.page_shortcuts.setObjectName("page_shortcuts")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_shortcuts)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.box_shortcuts = QtWidgets.QGroupBox(self.page_shortcuts)
        self.box_shortcuts.setObjectName("box_shortcuts")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.box_shortcuts)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.vLayout_shortcuts = QtWidgets.QVBoxLayout()
        self.vLayout_shortcuts.setObjectName("vLayout_shortcuts")
        self.hLayout_shortcut1 = QtWidgets.QHBoxLayout()
        self.hLayout_shortcut1.setContentsMargins(10, -1, 10, -1)
        self.hLayout_shortcut1.setObjectName("hLayout_shortcut1")
        self.label_shortcut1Name = QtWidgets.QLabel(self.box_shortcuts)
        self.label_shortcut1Name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shortcut1Name.setObjectName("label_shortcut1Name")
        self.hLayout_shortcut1.addWidget(self.label_shortcut1Name)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_shortcut1.addItem(spacerItem5)
        self.label_shortcut1 = QtWidgets.QLabel(self.box_shortcuts)
        self.label_shortcut1.setObjectName("label_shortcut1")
        self.hLayout_shortcut1.addWidget(self.label_shortcut1)
        self.vLayout_shortcuts.addLayout(self.hLayout_shortcut1)
        self.hLayout_shortcut2 = QtWidgets.QHBoxLayout()
        self.hLayout_shortcut2.setContentsMargins(10, -1, 10, -1)
        self.hLayout_shortcut2.setObjectName("hLayout_shortcut2")
        self.label_shortcut2Name = QtWidgets.QLabel(self.box_shortcuts)
        self.label_shortcut2Name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shortcut2Name.setObjectName("label_shortcut2Name")
        self.hLayout_shortcut2.addWidget(self.label_shortcut2Name)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_shortcut2.addItem(spacerItem6)
        self.label_shortcut2 = QtWidgets.QLabel(self.box_shortcuts)
        self.label_shortcut2.setObjectName("label_shortcut2")
        self.hLayout_shortcut2.addWidget(self.label_shortcut2)
        self.vLayout_shortcuts.addLayout(self.hLayout_shortcut2)
        self.pushButton_ok = QtWidgets.QPushButton(self.box_shortcuts)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.vLayout_shortcuts.addWidget(self.pushButton_ok)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vLayout_shortcuts.addItem(spacerItem7)
        self.gridLayout_5.addLayout(self.vLayout_shortcuts, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.box_shortcuts, 0, 0, 1, 1)
        self.stack.addWidget(self.page_shortcuts)
        self.gridLayout.addWidget(self.stack, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stack.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_bubble.setText(_translate("MainWindow", "Gaze Visalizaition"))
        self.pushButton_bubble.setText(_translate("MainWindow", "on"))
        self.box_database.setTitle(_translate("MainWindow", "Database"))
        self.label_id.setText(_translate("MainWindow", "ID:"))
        self.check_id.setText(_translate("MainWindow", "Apply"))
        self.pushButton_dbsetting.setText(_translate("MainWindow", "Database Setting"))
        self.pushButton_shortcuts.setText(_translate("MainWindow", "Shortcuts"))
        self.box_image.setTitle(_translate("MainWindow", "Image Size"))
        self.label_height.setText(_translate("MainWindow", "Height:"))
        self.label_heightPx.setText(_translate("MainWindow", "px"))
        self.label_ratio.setText(_translate("MainWindow", "Ratio:"))
        self.label_ratioPx.setText(_translate("MainWindow", "%"))
        self.label_width.setText(_translate("MainWindow", "Width:"))
        self.label_widthPx.setText(_translate("MainWindow", "px"))
        self.pushButton_calibrate.setText(_translate("MainWindow", "Calibrate"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.box_setting.setTitle(_translate("MainWindow", "Database Setting"))
        self.table.setSortingEnabled(False)
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Host"))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "USER"))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "PASSWORD"))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "DB_NAME"))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "CHARSET"))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "TABLE"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Setting"))
        self.pushButton_cancel.setText(_translate("MainWindow", "CANCEL"))
        self.pushButton_apply.setText(_translate("MainWindow", "APPLY"))
        self.box_shortcuts.setTitle(_translate("MainWindow", "Shortcuts"))
        self.label_shortcut1Name.setText(_translate("MainWindow", "Gaze Visualization\n"
"(On/Off)"))
        self.label_shortcut1.setText(_translate("MainWindow", "1"))
        self.label_shortcut2Name.setText(_translate("MainWindow", "Gaze Tracking\n"
"(Start/End)"))
        self.label_shortcut2.setText(_translate("MainWindow", "2"))
        self.pushButton_ok.setText(_translate("MainWindow", "OK"))

    def toggleName(self, object):
        if eq(object.text(), "on"):
            object.setText("off")
        else:
            object.setText("on")


class Board(QLabel):
    def __init__(self, parent):
        super().__init__(parent=parent)
        self.setAcceptDrops(True)

    def dragEnterEvent(self, e: QDragEnterEvent):
        if e.mimeData().hasUrls():
            e.accept()
        else:
            e.ignore()

    def dropEvent(self, e: QDropEvent):
        if e.mimeData().hasUrls():
            e.accept()
        else:
            e.ignore()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
